/* tslint:disable */
/* eslint-disable */
/**
 * Blankroom API
 * The Blankroom API description
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RoomApi } from './apis/room-api';
import { BoardApi } from './apis/board-api'
import { AuthApi } from './apis/auth-api';
import { Configuration } from './configuration';
import customAxios from './customAxios';

const bkPath = import.meta.env.VITE_REST_API_URL || 'http://localhost:3001';

const config = new Configuration({
  basePath: bkPath
});

const roomApi = new RoomApi(config, bkPath, customAxios);
const boardApi = new BoardApi(config, bkPath, customAxios);
const authApi = new AuthApi(config, bkPath, customAxios);

export { roomApi, boardApi, authApi, customAxios };