/* tslint:disable */
/* eslint-disable */
/**
 * Blankroom API
 * The Blankroom API description
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetBoardByRoomIdReturnType
 */
export interface GetBoardByRoomIdReturnType {

    /**
     * @type {string}
     * @memberof GetBoardByRoomIdReturnType
     */
    room_id: string;

    /**
     * @type {Blob}
     * @memberof GetBoardByRoomIdReturnType
     */
    image_data: Blob;

    /**
     * @type {Date}
     * @memberof GetBoardByRoomIdReturnType
     */
    created_at: Date;

    /**
     * @type {Date}
     * @memberof GetBoardByRoomIdReturnType
     */
    updated_at: Date;
}
