/* tslint:disable */
/* eslint-disable */
/**
 * Blankroom API
 * The Blankroom API description
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetRoomItemReturnDto
 */
export interface GetRoomItemReturnDto {

    /**
     * 방 ID
     *
     * @type {string}
     * @memberof GetRoomItemReturnDto
     */
    id: string;

    /**
     * @type {string}
     * @memberof GetRoomItemReturnDto
     */
    short_id: string;

    /**
     * @type {string}
     * @memberof GetRoomItemReturnDto
     */
    name: string;

    /**
     * @type {string}
     * @memberof GetRoomItemReturnDto
     */
    description: string;

    /**
     * @type {Date}
     * @memberof GetRoomItemReturnDto
     */
    created_at: Date;
}
