/* tslint:disable */
/* eslint-disable */
/**
 * Blankroom API
 * The Blankroom API description
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ListRoomsDto
 */
export interface ListRoomsDto {

    /**
     * 방 이름 (필수)
     *
     * @type {string}
     * @memberof ListRoomsDto
     */
    name: string;

    /**
     * 방 설명 (선택)
     *
     * @type {string}
     * @memberof ListRoomsDto
     */
    description?: string;

    /**
     * 숫자 6자리 비밀번호 (선택)
     *
     * @type {string}
     * @memberof ListRoomsDto
     */
    password?: string;

    /**
     * 방 짧은 ID (필수)
     *
     * @type {string}
     * @memberof ListRoomsDto
     */
    short_id: string;

    /**
     * 방 생성 시간 (필수)
     *
     * @type {Date}
     * @memberof ListRoomsDto
     */
    created_at: Date;
}
