/* tslint:disable */
/* eslint-disable */
/**
 * Blankroom API
 * The Blankroom API description
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface LoginDto
 */
export interface LoginDto {

    /**
     * @type {string}
     * @memberof LoginDto
     */
    username: string;

    /**
     * @type {string}
     * @memberof LoginDto
     */
    password: string;
}
