/* tslint:disable */
/* eslint-disable */
/**
 * Blankroom API
 * The Blankroom API description
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {

    /**
     * @type {string}
     * @memberof RegisterDto
     */
    nickname: string;

    /**
     * @type {string}
     * @memberof RegisterDto
     */
    id: string;

    /**
     * @type {string}
     * @memberof RegisterDto
     */
    password: string;
}
