/* tslint:disable */
/* eslint-disable */
/**
 * Blankroom API
 * The Blankroom API description
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UserJwtDto
 */
export interface UserJwtDto {

    /**
     * @type {string}
     * @memberof UserJwtDto
     */
    sub: string;

    /**
     * @type {string}
     * @memberof UserJwtDto
     */
    nickname: string;

    /**
     * @type {string}
     * @memberof UserJwtDto
     */
    createdAt: string;

    /**
     * @type {number}
     * @memberof UserJwtDto
     */
    iat: number;

    /**
     * @type {number}
     * @memberof UserJwtDto
     */
    exp: number;
}
